

type TeachingGroup {
	RefId: String
	SchoolYear: String
	LocalId: String
	ShortName: String
	LongName: String
	TimeTableSubjectRefId: String
	TeacherList: TeacherList
	TeachingGroupPeriodList: TeachingGroupPeriodList
}

type TeacherList {
	TeachingGroupTeacher: TeachingGroupTeacher
}

type TeachingGroupTeacher {
	StaffPersonalRefId: String
	StaffLocalId: String
	Name: Name
	Association: String
}

type Name {
	Type: String
	FamilyName: String
	GivenName: String
}

type TeachingGroupPeriodList {
	TeachingGroupPeriod: [TeachingGroupPeriod]
}

type TeachingGroupPeriod {
	RoomNumber: String
	DayId: String
	PeriodId: String
}