
type DemoQuery {
    TeachingGroupByName(fname: String!, gname: String!): [TeachingGroup]
    TeachingGroupByStaffID(staffid: String!): [TeachingGroup]
    TeachingGroup(teachinggroupid: String!): TeachingGroup
    GradingAssignment(tgid: String!): [GradingAssignment]
    StudentAttendance(studentid: String!): [StudentAttendanceTimeList]
    QueryXAPI(objid: String!): [XAPI]
    # --------------------------------------------------------------
    # GetStudentProgress(teachinggroupid: String!): [ProgressReport]
}

# ------------------------------------------------------------------

# type ProgressReport {
#     GivenName: String
#     FamilyName: String
#     DaysAbsent: String
#     ProgressResult: [ProgressResult]
# }

# type ProgressResult {
#     AssignmentDescription: String
#     Result: AssignmentResult
# }

# type AssignmentResult {
# 	completion: String  
# 	success: String     
# 	score: ScaledScore
# 	duration: String
# }

# type ScaledScore {
# 	scaled: String 
# 	min: String 
# 	max: String 
# }
