Path = "./config.toml"

[Global]
  ErrLog = "./log.txt"

[Filewatcher]
  DirSif = "./inbound/sif"
  DirXapi = "./inbound/xapi"

[Rest]
  Port = 1323
  SifPathS = "/sif"
  XapiPathS = "/xapi"  
  PathGQL = "/gql"

[RPC]
  Namespace = "GEqULGowEbxxea7meueSzz42jfFE9N1NJTXHCZWmsHt5"
  CtxSif = "demo-sif"
  CtxXapi = "demo-xapi"
  CtxMetaSif = "demo-sif-meta"
  CtxMetaXapi = "demo-xapi-meta"
  Server = "192.168.245.128"
  Port = 5777
