Path = "./config.toml"

[Global]
  ErrLog = "./log.txt"

[Filewatcher]
  DirSif = "./inbound/sif"
  DirXapi = "./inbound/xapi"

[Rest]
  Port = 1323
  SifPath = "/sif"
  XapiPath = "/xapi"

[RPC]
  Namespace = "Aa5fKf2UmyfCufY6JFmQpX12j1jjDFSUfbFUEE92t2nx"
  CtxSif = "abc-sif"
  CtxXapi = "abc-xapi"
  CtxMetaSif = "abc-sif-meta"
  CtxMetaXapi = "abc-xapi-meta"
  Server = "192.168.76.32"
  Port = 5777
