Path = "./config.toml"

[Global]
  ErrLog = "./log.txt"

[Filewatcher]
  DirSif = "./inbound/sif"
  DirXapi = "./inbound/xapi"

[Rest]
  Port = 1323
  PathSend = "/tonode"
  PathGQL = "/gql"   

[RPC]
  Namespace = "BQZjUdgi1NCtMLmjSu8d6VFp8Rh1NHmguu8YsGRv1pMv"
  Server = "192.168.76.49"
  Port = 5777
  Ctx = "demo"
  CtxMeta = "demo-meta"
