Path = "./config.toml"

[Global]
  ErrLog = "./log.txt"

[Filewatcher]
  DirSif = "./inbound/sif"
  DirXapi = "./inbound/xapi"

[Rest]
  Port = 1323
  SifPathS = "/sif"
  XapiPathS = "/xapi"  
  PathGQL = "/gql"

[RPC]
  Namespace = "75ZzVte8eYQpi71GZHBb8Z8idetADRCkkBW8YVRfryyw"
  CtxSif = "demo-sif"
  CtxXapi = "demo-xapi"
  CtxMetaSif = "demo-sif-meta"
  CtxMetaXapi = "demo-xapi-meta"
  Server = "192.168.76.32"
  Port = 5777
