Path = "./config.toml"

[Global]
  ErrLog = "./log.txt"

[Filewatcher]
  # DirSif = "./inbound/sif"
  # DirXapi = "./inbound/xapi"
  Dir = "./inbound/"

[Rest]
  Port = 1323
  PathSend = "/tonode"
  PathGQL = "/gql"   

[RPC]
  Namespace = "AFMVVCoii2B7aQrzb8a1hbSJVHLLxy39bvLMWjT4nbXP"
  Server = "192.168.245.132"
  Port = 5777
  Ctx = "demo"
  CtxMeta = "demo-meta"
