

type Overview {
	learning_area: String
	subject: String
	stage: String
	yrLvls: [String]
	overview: [String]
	concepts: [concepts]
	inquiry_skills: [inquiry_skills]
	tools: [tools]
}

type concepts {
	name: String
	description: String
}

type inquiry_skills {
	name: String
	skills: [skills]
}

type skills {
	skill: String
	ac: [String]
}

type tools {
	name: String
	examples: [String]
	code: String
}