type QueryRoot {
	xapi: xapi
}

type xapi {
	id: String
	actor: actor
	verb: verb
	object: object
	result: result
}

type actor {
	name: String
	mbox: String
}

type verb {
	id: String
	display: display
}

type display {
	en_US: String
}

type object {
	id: String
	definition: definition
}

type definition {
	type: String
	name: String
}

type result {
	completion: String
	success: String
	duration: String
	score: score
}

type score {
	scaled: String
	min: String
	max: String
}