type QueryRoot {
	xapi: xapi
}

type xapi {
	learning_area: String
	subject: String
	stage: String
	yrLvls: [String]
	courses: [courses]
}

type courses {
	name: String
	outcomes: [outcomes]
	inquiry_questions: [String]
	focus: String
	content_areas: [content_areas]
}

type outcomes {
	description: String
	id: String
}

type content_areas {
	name: String
	investigations: [investigations]
}

type investigations {
	description: String
	ac: [String]
	examples: [String]
}