

type StaffPersonal {
	RefId: String
	LocalId: String
	StateProvinceId: String
	OtherIdList: OtherIdList
	PersonInfo: PersonInfo
	Title: String
	EmploymentStatus: String
	MostRecent: MostRecent
}

type OtherIdList {
	OtherId: OtherId
}

type OtherId {
	Type: String
	content: String
}

type PersonInfo {
	Name: Name
	OtherNames: OtherNames
	Demographics: Demographics
	AddressList: AddressList
	PhoneNumberList: PhoneNumberList
	EmailList: EmailList
}

type Name {
	Type: String
	FamilyName: String
	GivenName: String
	FullName: String
}

type OtherNames {
	Name: [Name]
}

type Demographics {
	IndigenousStatus: String
	Sex: String
	BirthDate: String
	BirthDateVerification: String
	PlaceOfBirth: String
	StateOfBirth: String
	CountryOfBirth: String
	CountriesOfCitizenship: CountriesOfCitizenship
	CountriesOfResidency: CountriesOfResidency
	CountryArrivalDate: String
	AustralianCitizenshipStatus: String
	EnglishProficiency: EnglishProficiency
	LanguageList: LanguageList
	DwellingArrangement: DwellingArrangement
	Religion: Religion
	ReligiousEventList: ReligiousEventList
	ReligiousRegion: String
	PermanentResident: String
	VisaSubClass: String
	VisaStatisticalCode: String
}

type CountriesOfCitizenship {
	CountryOfCitizenship: [String]
}

type CountriesOfResidency {
	CountryOfResidency: [String]
}

type EnglishProficiency {
	Code: String
}

type LanguageList {
	Language: Language
}

type Language {
	Code: String
	LanguageType: String
}

type DwellingArrangement {
	Code: String
}

type Religion {
	Code: String
}

type ReligiousEventList {
	ReligiousEvent: [ReligiousEvent]
}

type ReligiousEvent {
	Type: String
	Date: String
}

type AddressList {
	Address: [Address]
}

type Address {
	Type: String
	Role: String
	Street: Street
	City: String
	StateProvince: String
	Country: String
	PostalCode: String
}

type Street {
	Line1: String
	Line2: String
}

type PhoneNumberList {
	PhoneNumber: [PhoneNumber]
}

type PhoneNumber {
	Type: String
	Number: String
	Extension: String
	ListedStatus: String
}

type EmailList {
	Email: [Email]
}

type Email {
	Type: String
	content: String
}

type MostRecent {
	SchoolLocalId: String
	LocalCampusId: String
	NAPLANClassList: NAPLANClassList
	HomeGroup: String
}

type NAPLANClassList {
	ClassCode: [String]
}